language: node_js

node_js:
  - "6"

sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - redis-server

before_script:
  - npm install -g mocha

script:
  - npm run nyc
