language: node_js

node_js:
  - "6"

before_install:
  - mysql -e "create database IF NOT EXISTS starter;" -uroot

services:
  - redis-server
  - mysql

before_script:
  - npm install -g mocha

script:
  - npm run nyc
